# 
set ( RECLUSE_GRAPHICS_INCLUDE ${RECLUSE_FRAMEWORK_INCLUDE}/Recluse/Graphics )
set ( RECLUSE_GRAPHICS_SOURCE ${RECLUSE_FRAMEWORK_SOURCE}/Graphics )

set ( RECLUSE_GRAPHICS_BUILD
    ${RECLUSE_GRAPHICS_INCLUDE}/GraphicsInstance.hpp
    ${RECLUSE_GRAPHICS_INCLUDE}/CommandList.hpp
    ${RECLUSE_GRAPHICS_INCLUDE}/CommandHandler.hpp
    #${RECLUSE_GRAPHICS_INCLUDE}/CommandQueue.hpp
    ${RECLUSE_GRAPHICS_INCLUDE}/DescriptorSet.hpp
    ${RECLUSE_GRAPHICS_INCLUDE}/Format.hpp
    ${RECLUSE_GRAPHICS_INCLUDE}/GraphicsDevice.hpp
    ${RECLUSE_GRAPHICS_INCLUDE}/GraphicsAdapter.hpp
    ${RECLUSE_GRAPHICS_INCLUDE}/PipelineState.hpp
    ${RECLUSE_GRAPHICS_INCLUDE}/RenderPass.hpp
    ${RECLUSE_GRAPHICS_INCLUDE}/RenderPassMap.hpp
    ${RECLUSE_GRAPHICS_INCLUDE}/Resource.hpp
    ${RECLUSE_GRAPHICS_INCLUDE}/ResourceView.hpp
	${RECLUSE_GRAPHICS_INCLUDE}/ShaderProgram.hpp
    ${RECLUSE_GRAPHICS_INCLUDE}/Shader.hpp
    ${RECLUSE_GRAPHICS_SOURCE}/Shader.cpp
    ${RECLUSE_GRAPHICS_SOURCE}/ShaderMap.hpp
    ${RECLUSE_GRAPHICS_SOURCE}/ShaderMap.cpp
    ${RECLUSE_GRAPHICS_INCLUDE}/VideoMemoryPool.hpp
    ${RECLUSE_GRAPHICS_SOURCE}/DeviceFactory.cpp
    ${RECLUSE_GRAPHICS_SOURCE}/RenderPass.cpp
    ${RECLUSE_GRAPHICS_SOURCE}/RenderPassMap.cpp
	${RECLUSE_GRAPHICS_SOURCE}/ShaderProgram.cpp
    ${RECLUSE_GRAPHICS_INCLUDE}/GraphicsCommon.hpp
)

set ( RECLUSE_FRAMEWORK_COMPILE_FILES
    ${RECLUSE_FRAMEWORK_COMPILE_FILES}
    ${RECLUSE_GRAPHICS_BUILD}
)